// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__f32toa = 32
)

const (
    _stack__f32toa = 64
)

const (
    _size__f32toa = 3664
)

var (
    _pcsp__f32toa = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x8e3, 64},
        {0x8e4, 48},
        {0x8e6, 40},
        {0x8e8, 32},
        {0x8ea, 24},
        {0x8ec, 16},
        {0x8ed, 8},
        {0x8f1, 0},
        {0xe50, 64},
    }
)

var _cfunc_f32toa = []loader.CFunc{
    {"_f32toa_entry", 0,  _entry__f32toa, 0, nil},
    {"_f32toa", _entry__f32toa, _size__f32toa, _stack__f32toa, _pcsp__f32toa},
}
