// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__quote = 144
)

const (
    _stack__quote = 104
)

const (
    _size__quote = 3022
)

var (
    _pcsp__quote = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0xb92, 104},
        {0xb93, 48},
        {0xb95, 40},
        {0xb97, 32},
        {0xb99, 24},
        {0xb9b, 16},
        {0xb9c, 8},
        {0xba0, 0},
        {0xbce, 104},
    }
)

var _cfunc_quote = []loader.CFunc{
    {"_quote_entry", 0,  _entry__quote, 0, nil},
    {"_quote", _entry__quote, _size__quote, _stack__quote, _pcsp__quote},
}
