// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__unquote = 48
)

const (
    _stack__unquote = 80
)

const (
    _size__unquote = 2336
)

var (
    _pcsp__unquote = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x6ca, 80},
        {0x6cb, 48},
        {0x6cd, 40},
        {0x6cf, 32},
        {0x6d1, 24},
        {0x6d3, 16},
        {0x6d4, 8},
        {0x6d8, 0},
        {0x920, 80},
    }
)

var _cfunc_unquote = []loader.CFunc{
    {"_unquote_entry", 0,  _entry__unquote, 0, nil},
    {"_unquote", _entry__unquote, _size__unquote, _stack__unquote, _pcsp__unquote},
}
