// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__value = 624
)

const (
    _stack__value = 128
)

const (
    _size__value = 13092
)

var (
    _pcsp__value = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x11c3, 128},
        {0x11c4, 48},
        {0x11c6, 40},
        {0x11c8, 32},
        {0x11ca, 24},
        {0x11cc, 16},
        {0x11cd, 8},
        {0x11d1, 0},
        {0x3324, 128},
    }
)

var _cfunc_value = []loader.CFunc{
    {"_value_entry", 0,  _entry__value, 0, nil},
    {"_value", _entry__value, _size__value, _stack__value, _pcsp__value},
}
