// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__value = 576
)

const (
    _stack__value = 128
)

const (
    _size__value = 12364
)

var (
    _pcsp__value = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x10fc, 128},
        {0x10fd, 48},
        {0x10ff, 40},
        {0x1101, 32},
        {0x1103, 24},
        {0x1105, 16},
        {0x1106, 8},
        {0x110a, 0},
        {0x304c, 128},
    }
)

var _cfunc_value = []loader.CFunc{
    {"_value_entry", 0,  _entry__value, 0, nil},
    {"_value", _entry__value, _size__value, _stack__value, _pcsp__value},
}
