// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__value = 576
)

const (
    _stack__value = 128
)

const (
    _size__value = 12412
)

var (
    _pcsp__value = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x1115, 128},
        {0x1116, 48},
        {0x1118, 40},
        {0x111a, 32},
        {0x111c, 24},
        {0x111e, 16},
        {0x111f, 8},
        {0x1123, 0},
        {0x307c, 128},
    }
)

var _cfunc_value = []loader.CFunc{
    {"_value_entry", 0,  _entry__value, 0, nil},
    {"_value", _entry__value, _size__value, _stack__value, _pcsp__value},
}
