// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__vnumber = 128
)

const (
    _stack__vnumber = 136
)

const (
    _size__vnumber = 8392
)

var (
    _pcsp__vnumber = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0xcda, 136},
        {0xcdb, 48},
        {0xcdd, 40},
        {0xcdf, 32},
        {0xce1, 24},
        {0xce3, 16},
        {0xce4, 8},
        {0xce8, 0},
        {0x20c8, 136},
    }
)

var _cfunc_vnumber = []loader.CFunc{
    {"_vnumber_entry", 0,  _entry__vnumber, 0, nil},
    {"_vnumber", _entry__vnumber, _size__vnumber, _stack__vnumber, _pcsp__vnumber},
}
