// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__vstring = 144
)

const (
    _stack__vstring = 88
)

const (
    _size__vstring = 2344
)

var (
    _pcsp__vstring = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x85b, 88},
        {0x85c, 48},
        {0x85e, 40},
        {0x860, 32},
        {0x862, 24},
        {0x864, 16},
        {0x865, 8},
        {0x869, 0},
        {0x928, 88},
    }
)

var _cfunc_vstring = []loader.CFunc{
    {"_vstring_entry", 0,  _entry__vstring, 0, nil},
    {"_vstring", _entry__vstring, _size__vstring, _stack__vstring, _pcsp__vstring},
}
