// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__vunsigned = 0
)

const (
    _stack__vunsigned = 24
)

const (
    _size__vunsigned = 372
)

var (
    _pcsp__vunsigned = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x7, 16},
        {0x53, 24},
        {0x55, 16},
        {0x56, 8},
        {0x57, 0},
        {0x62, 24},
        {0x64, 16},
        {0x65, 8},
        {0x66, 0},
        {0x7d, 24},
        {0x7f, 16},
        {0x80, 8},
        {0x81, 0},
        {0x12a, 24},
        {0x12c, 16},
        {0x12d, 8},
        {0x12e, 0},
        {0x161, 24},
        {0x163, 16},
        {0x164, 8},
        {0x165, 0},
        {0x16d, 24},
        {0x16f, 16},
        {0x170, 8},
        {0x174, 0},
    }
)

var _cfunc_vunsigned = []loader.CFunc{
    {"_vunsigned_entry", 0,  _entry__vunsigned, 0, nil},
    {"_vunsigned", _entry__vunsigned, _size__vunsigned, _stack__vunsigned, _pcsp__vunsigned},
}
