// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__quote = 48
)

const (
    _stack__quote = 104
)

const (
    _size__quote = 1981
)

var (
    _pcsp__quote = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x784, 104},
        {0x785, 48},
        {0x787, 40},
        {0x789, 32},
        {0x78b, 24},
        {0x78d, 16},
        {0x78e, 8},
        {0x78f, 0},
        {0x7bd, 104},
    }
)

var _cfunc_quote = []loader.CFunc{
    {"_quote_entry", 0,  _entry__quote, 0, nil},
    {"_quote", _entry__quote, _size__quote, _stack__quote, _pcsp__quote},
}
