// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__value = 224
)

const (
    _stack__value = 128
)

const (
    _size__value = 12176
)

var (
    _pcsp__value = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x20c, 128},
        {0x20d, 48},
        {0x20f, 40},
        {0x211, 32},
        {0x213, 24},
        {0x215, 16},
        {0x216, 8},
        {0x217, 0},
        {0x2f90, 128},
    }
)

var _cfunc_value = []loader.CFunc{
    {"_value_entry", 0,  _entry__value, 0, nil},
    {"_value", _entry__value, _size__value, _stack__value, _pcsp__value},
}
