// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__vnumber = 48
)

const (
    _stack__vnumber = 136
)

const (
    _size__vnumber = 7784
)

var (
    _pcsp__vnumber = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x1e5a, 136},
        {0x1e5b, 48},
        {0x1e5d, 40},
        {0x1e5f, 32},
        {0x1e61, 24},
        {0x1e63, 16},
        {0x1e64, 8},
        {0x1e68, 0},
    }
)

var _cfunc_vnumber = []loader.CFunc{
    {"_vnumber_entry", 0,  _entry__vnumber, 0, nil},
    {"_vnumber", _entry__vnumber, _size__vnumber, _stack__vnumber, _pcsp__vnumber},
}
