// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__vsigned = 0
)

const (
    _stack__vsigned = 16
)

const (
    _size__vsigned = 372
)

var (
    _pcsp__vsigned = [][2]uint32{
        {0x1, 0},
        {0x5, 8},
        {0x78, 16},
        {0x79, 8},
        {0x7a, 0},
        {0x85, 16},
        {0x86, 8},
        {0x87, 0},
        {0x127, 16},
        {0x128, 8},
        {0x129, 0},
        {0x12d, 16},
        {0x12e, 8},
        {0x12f, 0},
        {0x165, 16},
        {0x166, 8},
        {0x167, 0},
        {0x172, 16},
        {0x173, 8},
        {0x174, 0},
    }
)

var _cfunc_vsigned = []loader.CFunc{
    {"_vsigned_entry", 0,  _entry__vsigned, 0, nil},
    {"_vsigned", _entry__vsigned, _size__vsigned, _stack__vsigned, _pcsp__vsigned},
}
