// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__vstring = 64
)

const (
    _stack__vstring = 112
)

const (
    _size__vstring = 2704
)

var (
    _pcsp__vstring = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x9d5, 112},
        {0x9d6, 48},
        {0x9d8, 40},
        {0x9da, 32},
        {0x9dc, 24},
        {0x9de, 16},
        {0x9df, 8},
        {0x9e0, 0},
        {0xa90, 112},
    }
)

var _cfunc_vstring = []loader.CFunc{
    {"_vstring_entry", 0,  _entry__vstring, 0, nil},
    {"_vstring", _entry__vstring, _size__vstring, _stack__vstring, _pcsp__vstring},
}
